/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegionesRouteImport } from './routes/regiones'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ExperimentosRouteImport } from './routes/experimentos'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AudienciasRouteImport } from './routes/audiencias'
import { Route as ArquitecturaRouteImport } from './routes/arquitectura'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'

const RegionesRoute = RegionesRouteImport.update({
  id: '/regiones',
  path: '/regiones',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentosRoute = ExperimentosRouteImport.update({
  id: '/experimentos',
  path: '/experimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienciasRoute = AudienciasRouteImport.update({
  id: '/audiencias',
  path: '/audiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquitecturaRoute = ArquitecturaRouteImport.update({
  id: '/arquitectura',
  path: '/arquitectura',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/audiencias': typeof AudienciasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/eventos': typeof EventosRoute
  '/experimentos': typeof ExperimentosRoute
  '/productos': typeof ProductosRoute
  '/regiones': typeof RegionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/audiencias': typeof AudienciasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/eventos': typeof EventosRoute
  '/experimentos': typeof ExperimentosRoute
  '/productos': typeof ProductosRoute
  '/regiones': typeof RegionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/audiencias': typeof AudienciasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/eventos': typeof EventosRoute
  '/experimentos': typeof ExperimentosRoute
  '/productos': typeof ProductosRoute
  '/regiones': typeof RegionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/arquitectura'
    | '/audiencias'
    | '/configuracion'
    | '/eventos'
    | '/experimentos'
    | '/productos'
    | '/regiones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/arquitectura'
    | '/audiencias'
    | '/configuracion'
    | '/eventos'
    | '/experimentos'
    | '/productos'
    | '/regiones'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/arquitectura'
    | '/audiencias'
    | '/configuracion'
    | '/eventos'
    | '/experimentos'
    | '/productos'
    | '/regiones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ArquitecturaRoute: typeof ArquitecturaRoute
  AudienciasRoute: typeof AudienciasRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EventosRoute: typeof EventosRoute
  ExperimentosRoute: typeof ExperimentosRoute
  ProductosRoute: typeof ProductosRoute
  RegionesRoute: typeof RegionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regiones': {
      id: '/regiones'
      path: '/regiones'
      fullPath: '/regiones'
      preLoaderRoute: typeof RegionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experimentos': {
      id: '/experimentos'
      path: '/experimentos'
      fullPath: '/experimentos'
      preLoaderRoute: typeof ExperimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiencias': {
      id: '/audiencias'
      path: '/audiencias'
      fullPath: '/audiencias'
      preLoaderRoute: typeof AudienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquitectura': {
      id: '/arquitectura'
      path: '/arquitectura'
      fullPath: '/arquitectura'
      preLoaderRoute: typeof ArquitecturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ArquitecturaRoute: ArquitecturaRoute,
  AudienciasRoute: AudienciasRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EventosRoute: EventosRoute,
  ExperimentosRoute: ExperimentosRoute,
  ProductosRoute: ProductosRoute,
  RegionesRoute: RegionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
