from __future__ import annotations

from enum import Enum


class EventType(str, Enum):
    LOGIN = "LOGIN"
    SEARCH = "SEARCH"
    PAGE_VIEW = "PAGE_VIEW"
    VIEW_PRODUCT = "VIEW_PRODUCT"
    ADD_TO_CART = "ADD_TO_CART"
    REMOVE_FROM_CART = "REMOVE_FROM_CART"
    PURCHASE = "PURCHASE"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    GPS_UPDATE = "GPS_UPDATE"
    IOT_READING = "IOT_READING"
    MOTION_DETECTED = "MOTION_DETECTED"
    SOCIAL_POST = "SOCIAL_POST"


class AgentProfile(str, Enum):
    COMPRADOR_COMPULSIVO = "COMPRADOR_COMPULSIVO"
    COMPARADOR = "COMPARADOR"
    COMPRADOR_NOCTURNO = "COMPRADOR_NOCTURNO"
    CLIENTE_PREMIUM = "CLIENTE_PREMIUM"
    CLIENTE_FRECUENTE = "CLIENTE_FRECUENTE"
    USUARIO_EXPLORADOR = "USUARIO_EXPLORADOR"
    CLIENTE_INDECISO = "CLIENTE_INDECISO"
    CLIENTE_ESTACIONAL = "CLIENTE_ESTACIONAL"


class Scenario(str, Enum):
    BASE = "BASE"
    NAVIDAD = "NAVIDAD"
    CYBER_MONDAY = "CYBER_MONDAY"
    BLACK_FRIDAY = "BLACK_FRIDAY"
    FIESTAS_PATRIAS = "FIESTAS_PATRIAS"
    CAMPANA_ESCOLAR = "CAMPANA_ESCOLAR"
    DIA_DEL_PADRE = "DIA_DEL_PADRE"


class SourceHint(str, Enum):
    WEB = "WEB"
    MOBILE = "MOBILE"
    IOT = "IOT"
    VEHICLE = "VEHICLE"
    POS = "POS"


class AgentState(str, Enum):
    OFFLINE = "OFFLINE"
    HOME = "HOME"
    PRODUCT = "PRODUCT"
    CART = "CART"
